In [14]:
# dataset, vlasificador de imagenes
import torch
from torch.utils.data import Dataset, DataLoader, TensorDataset
from torchvision import datasets, transforms
import ssl

In [2]:
ssl._create_default_https_context = ssl._create_unverified_context

In [ ]:
# transformacion que se aplica a cada imagen
# convertiomos la imagen a un tensor y la redimensionamos a 64x64
transformaciones = transforms.Compose([
    transforms.Resize((64, 64)),
    transforms.ToTensor()
])

In [5]:
dataset_mnist = datasets.MNIST(
    root='data',
    train=True,
    transform=transformaciones,
    download=True
)

100%|██████████| 9.91M/9.91M [00:05<00:00, 1.68MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 390kB/s]
100%|██████████| 1.65M/1.65M [00:01<00:00, 1.24MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 3.41MB/s]


In [7]:
cargar_datos = DataLoader(dataset_mnist,batch_size=32, shuffle=True)

In [8]:
cargar_datos

In [11]:
for lote, (dato, etiqueta) in enumerate(cargar_datos):
    print(f"Lote: {lote} -> Datos: {dato.shape}, Objetivo: {etiqueta.shape}")
    if lote == 5:
        break

Lote: 0 -> Datos: torch.Size([32, 1, 64, 64]), Objetivo: torch.Size([32])
Lote: 1 -> Datos: torch.Size([32, 1, 64, 64]), Objetivo: torch.Size([32])
Lote: 2 -> Datos: torch.Size([32, 1, 64, 64]), Objetivo: torch.Size([32])
Lote: 3 -> Datos: torch.Size([32, 1, 64, 64]), Objetivo: torch.Size([32])
Lote: 4 -> Datos: torch.Size([32, 1, 64, 64]), Objetivo: torch.Size([32])
Lote: 5 -> Datos: torch.Size([32, 1, 64, 64]), Objetivo: torch.Size([32])


In [18]:
datos = torch.randn(100,3)
print(datos)

etiquetas = torch.randint(0,2,(100,))
print(etiqueta)

dataset = TensorDataset(datos,etiquetas)

data_loader = DataLoader(dataset, batch_size=10, shuffle=True)

for datos_lote, etiquetas_lote in data_loader:
    print(f"Datos \n {datos_lote}")
    print(f"Etiqueta: \n {etiquetas_lote}")
    print("\n")

tensor([[-4.2564e-01, -1.7646e+00,  4.1997e-01],
        [ 5.3741e-01, -1.0952e+00, -3.6364e-02],
        [-5.2475e-01, -1.0185e+00,  1.0032e+00],
        [-1.6272e+00,  1.1938e+00, -3.6653e-01],
        [ 5.8977e-01, -1.6019e+00, -3.6750e-01],
        [-1.1086e+00,  2.7787e-03, -1.0596e+00],
        [-2.8585e-01,  6.0734e-02,  9.6624e-01],
        [-8.4467e-01, -7.2236e-02, -1.1057e+00],
        [ 7.7669e-01,  5.3269e-03,  1.0352e+00],
        [-1.6834e+00,  5.2957e-01, -1.0281e+00],
        [ 4.2645e-01, -4.1259e-01, -6.4883e-01],
        [ 6.2314e-01, -1.3841e+00, -6.6181e-01],
        [ 1.1537e+00,  1.1182e-03,  1.3466e+00],
        [-1.3738e-01,  2.9813e+00,  9.3296e-01],
        [-4.5110e-01, -5.7924e-01, -3.9964e-01],
        [-3.3316e-01, -3.4674e-01, -1.3371e+00],
        [-1.1673e+00,  3.3420e-01,  2.1657e-01],
        [ 1.5304e-01,  4.1692e-02, -6.1557e-01],
        [ 8.9527e-01,  7.5754e-01, -5.4911e-01],
        [ 4.9651e-01, -1.2287e+00, -1.0534e+00],
        [-1.1131e+00

In [13]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(tensor.device)

cuda:0


In [17]:
# tensor concatenado
tensor1 = torch.rand(2, 3)
tensor2 = torch.rand(2, 3)
print(tensor1)
print(tensor2)
#concatenacion
tensor_concat = torch.cat((tensor1, tensor2), dim=0)
print(tensor_concat)
#operaacion aritmetica
tensor_sum = tensor1 + tensor2
print(tensor_sum)
#operacion elemento a elemento
tensor_mul = tensor1 * tensor2  

tensor([[4.1667e-01, 6.4939e-01, 9.6440e-05],
        [5.5401e-01, 1.9666e-01, 9.1626e-01]])
tensor([[0.2392, 0.1212, 0.8013],
        [0.3705, 0.5759, 0.6710]])
tensor([[4.1667e-01, 6.4939e-01, 9.6440e-05],
        [5.5401e-01, 1.9666e-01, 9.1626e-01],
        [2.3916e-01, 1.2125e-01, 8.0130e-01],
        [3.7052e-01, 5.7589e-01, 6.7095e-01]])
tensor([[0.6558, 0.7706, 0.8014],
        [0.9245, 0.7726, 1.5872]])


In [35]:
random_image = torch.rand(3, 3, 3)  # Simulando una imagen RGB de 224x224
print(random_image.shape)
print(random_image)

torch.Size([3, 3, 3])
tensor([[[0.8483, 0.2113, 0.7139],
         [0.8996, 0.5545, 0.8162],
         [0.3732, 0.4289, 0.3636]],

        [[0.3339, 0.5780, 0.6216],
         [0.7284, 0.5181, 0.8708],
         [0.2851, 0.5678, 0.1710]],

        [[0.5892, 0.7760, 0.7607],
         [0.4653, 0.6813, 0.6214],
         [0.0975, 0.4708, 0.3013]]])


In [37]:
#imagen simulada
image = torch.tensor([[
    [0,128,255],
    [1,128,192],
    [2,64,96]
    ]])  # 3 canales (RGB), 3x3 pixeles
print(image.shape)
#acceso a un canal
red_channel = image[0,:,:]  # Canal rojo
print(red_channel.shape)
#acceso a un pixel
pixel_value = image[0,1, 1]  # Pixel en la posicion (1, 1)
print(pixel_value)

torch.Size([1, 3, 3])
torch.Size([3, 3])
tensor(128)


In [39]:
image_transformada = image * 2
print(image_transformada)

tensor([[[  0, 256, 510],
         [  2, 256, 384],
         [  4, 128, 192]]])


In [40]:
#deriavada
x = torch.tensor(3.0, requires_grad=True)
y = x**2
y.backward()
print(x.grad)  # Deberia imprimir 6.0, que es la derivada de y = x^2 en x = 3
print(y)  # Imprime el valor de y

tensor(6.)
tensor(9., grad_fn=<PowBackward0>)


In [41]:
# regresion lineal con pytorch
import torch
import torch.nn as nn
import torch.optim as optim

# Datos de ejemplo
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y = torch.tensor([[2.0], [4.0], [6.0], [8.0]])

# Definir el modelo
model = nn.Linear(1, 1)
# Definir la funcion de perdida y el optimizador
nn.init.xavier_uniform_(model.weight)
nn.init.constant_(model.bias, 0.0)

perdida_mlseloss = nn.MSELoss()
optimizador = optim.Adam(model.parameters(), lr=0.01)

# Entrenamiento del modelo
for epoch in range(1000):
    y_pred = model(X)
    perdida = perdida_mlseloss(y_pred, y)
    print(f'Epoch {epoch+1}, Loss: {perdida.item()}')
    optimizador.zero_grad()
    perdida.backward()
    optimizador.step()

with torch.no_grad():
    nueva_inversion = torch.tensor([[60]],dtype=torch.float32) / 50.0
    prediccion_retorno = model(nueva_inversion) * 50.0
    print(f'Prediccion de retorno para una inversion de 60: {prediccion_retorno.item()}')

Epoch 1, Loss: 50.774444580078125
Epoch 2, Loss: 50.25541305541992
Epoch 3, Loss: 49.73915100097656
Epoch 4, Loss: 49.2257080078125
Epoch 5, Loss: 48.71512985229492
Epoch 6, Loss: 48.207462310791016
Epoch 7, Loss: 47.70275115966797
Epoch 8, Loss: 47.201026916503906
Epoch 9, Loss: 46.70233917236328
Epoch 10, Loss: 46.20672607421875
Epoch 11, Loss: 45.714229583740234
Epoch 12, Loss: 45.224884033203125
Epoch 13, Loss: 44.73872375488281
Epoch 14, Loss: 44.255775451660156
Epoch 15, Loss: 43.776084899902344
Epoch 16, Loss: 43.29967498779297
Epoch 17, Loss: 42.826576232910156
Epoch 18, Loss: 42.35680389404297
Epoch 19, Loss: 41.89039611816406
Epoch 20, Loss: 41.427371978759766
Epoch 21, Loss: 40.967750549316406
Epoch 22, Loss: 40.51155090332031
Epoch 23, Loss: 40.05879211425781
Epoch 24, Loss: 39.60948181152344
Epoch 25, Loss: 39.16365051269531
Epoch 26, Loss: 38.721290588378906
Epoch 27, Loss: 38.28242874145508
Epoch 28, Loss: 37.847068786621094
Epoch 29, Loss: 37.41521453857422
Epoch 30, Lo