In [1]:
import numpy as np
import pandas as pd

In [2]:
#Version Pandas

pd.__version__

'2.3.2'

In [3]:
!wget 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'

"wget" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.


In [4]:
dataframe = pd.read_csv('../data/car_fuel_efficiency.csv')

In [5]:
dataframe.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [6]:
dataframe.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [7]:
# Records 

dataframe.shape

(9704, 11)

In [8]:
# Fuel types

dataframe['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [9]:
# Null values

dataframe.isnull().any().sum()

np.int64(4)

In [10]:
# Fuel efficiency 

dataframe[(dataframe['origin'] == 'Asia')]['fuel_efficiency_mpg'].describe()

count    3247.000000
mean       14.973830
std         2.578345
min         6.886245
25%        13.252010
50%        15.034670
75%        16.726318
max        23.759123
Name: fuel_efficiency_mpg, dtype: float64

In [11]:
dataframe.horsepower.isnull().unique()

array([False,  True])

In [12]:
dataframe.horsepower.mean()

np.float64(149.65729212983547)

In [13]:
frame_copy= dataframe.copy()

In [14]:
horsepower_mean_null = frame_copy.horsepower.mean()

In [15]:
frame_copy['horsepower'] = frame_copy['horsepower'].fillna(dataframe.horsepower.mean())

In [16]:
horsepower_mean_notnull = frame_copy['horsepower'].mean()

In [17]:
#Horsepower

horsepower_mean_notnull > horsepower_mean_null

np.True_

In [18]:
horsepower_mean_notnull , horsepower_mean_null

(np.float64(149.6572921298355), np.float64(149.65729212983547))

In [19]:
frame_copy = frame_copy[(dataframe['origin'] == 'Asia') ].loc[:,['vehicle_weight','model_year']].copy()

In [20]:
frame_copy.head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [21]:
frame_copy.iloc[:7,:]

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [22]:
X = frame_copy.iloc[:7,:].to_numpy()

In [23]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [24]:
XTX = X.T.dot(X)

In [25]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [26]:
INV = np.linalg.inv(XTX)

In [27]:
t = INV.dot(X.T)

In [28]:
t

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

In [29]:
Y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [30]:
w = t.dot(Y)

In [31]:
w

array([0.01386421, 0.5049067 ])

In [32]:
#Sum

np.sum(w)

np.float64(0.5187709081074023)