In [1]:
import numpy as np

In [3]:
np.__version__

'2.3.3'

In [4]:
np.zeros(2)

array([0., 0.])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones(1)

array([1.])

In [9]:
np.ones((3,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [11]:
x = np.array([1,2,3,4,5,6,7])

In [12]:
x[:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
x[3:5]

array([4, 5])

In [14]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [19]:
np.complex64?

Init signature: np.complex64(self, /, *args, **kwargs)
Docstring:     
Complex number type composed of two single-precision floating-point
numbers.

:Character code: ``'F'``
:Canonical name: `numpy.csingle`
:Alias on this platform (win32 AMD64): `numpy.complex64`: Complex number type composed of 2 32-bit-precision floating-point numbers.
File:           c:\users\dell\.conda\envs\de-zoomcap-2024\lib\site-packages\numpy\__init__.py
Type:           type
Subclasses:     

## Matriz

In [20]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.array([
    [0,1,2],
    [4,5,6],
    [7,8,9]])

array([[0, 1, 2],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.arange(0,20).reshape((5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
X = np.arange(0,20).reshape((5,4))

In [26]:
X.ndim

2

In [27]:
X.size

20

In [28]:
X.shape

(5, 4)

In [31]:
np.random.rand(3,3)

array([[0.03153359, 0.86490947, 0.69937414],
       [0.55818404, 0.49511699, 0.28688252],
       [0.29066406, 0.98906488, 0.83569385]])

In [32]:
X[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [33]:
X[2]

array([ 8,  9, 10, 11])

In [34]:
X[:,2]

array([ 2,  6, 10, 14, 18])

In [35]:
X[0,:]

array([0, 1, 2, 3])

Vector Operations

In [49]:
#Mult
np.random.seed(1)
x = np.random.randint(1,10,5)
y = np.random.randint(30,40,5)

In [50]:
x,y

(array([6, 9, 6, 1, 1], dtype=int32), array([31, 37, 36, 39, 32], dtype=int32))

In [51]:
2 * x

array([12, 18, 12,  2,  2], dtype=int32)

In [52]:
x + y

array([37, 46, 42, 40, 33], dtype=int32)

In [53]:
x * y

array([186, 333, 216,  39,  32], dtype=int32)

In [55]:
z = y.reshape(1,5)

In [60]:
#Dot product
x.dot(y)

np.int32(806)

In [65]:
A = np.random.rand(3,5)

In [66]:
A

array([[0.93912779, 0.77838924, 0.71597052, 0.8027575 , 0.09280081],
       [0.51815255, 0.86502025, 0.82914691, 0.82960336, 0.27304997],
       [0.0592432 , 0.67052804, 0.59306552, 0.6716541 , 0.41178788]])

In [69]:
A.dot(x)

array([17.83165127, 16.97163234, 11.03204665])

In [75]:
B = np.array([[6],[8],[1]])

In [76]:
B

array([[6],
       [8],
       [1]])

In [78]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])